import { test, expect } from '@playwright/test'
import { useDemoApi } from './demo'

for (const lang of ['zh', 'en'] as const)
  test(`${lang}: changing the trend range preserves cumulative KPIs`, async ({ page }) => {
    await useDemoApi(page, { lang })
    await page.goto('/admin/spend')
    await expect(page.getByRole('heading', { name: lang === 'zh' ? '费用' : 'Spend', exact: true })).toBeVisible()
    const cost = page
      .getByText(lang === 'zh' ? '实际费用（人民币）' : 'Actual cost (CNY)', { exact: true })
      .first()
      .locator('..')
    await expect(cost).toContainText('246.80')
    await expect(page.getByRole('row')).toHaveCount(8)
    await page.getByRole('radio', { name: lang === 'zh' ? '30 天' : '30 days', exact: true }).click()
    await expect(page.getByRole('row')).toHaveCount(31)
    await expect(cost).toContainText('246.80')
    await expect(page.getByText(lang === 'zh' ? '已完成' : 'Completed', { exact: true })).toBeVisible()
  })
test('admin mutations name the target and require confirmation', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/admin/users')
  let posts = 0
  page.on('request', (r) => {
    if (r.method() === 'POST' && r.url().includes('/admin/users/')) posts++
  })
  await page.getByRole('button', { name: '管理 creator1@example.com' }).click()
  await page.getByRole('menuitem', { name: '设为管理员', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('creator1@example.com')
  await expect(dialog).toContainText('管理所有用户')
  expect(posts).toBe(0)
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  expect(posts).toBe(0)
  await page.getByRole('button', { name: '管理 creator1@example.com' }).click()
  await page.getByRole('menuitem', { name: '停用账号' }).click()
  await page.getByRole('dialog').getByRole('button', { name: '确认修改' }).click()
  await expect(page.getByRole('row').filter({ hasText: 'creator1@example.com' })).toContainText('已停用')
  expect(posts).toBe(1)
})
test('grant validates amounts and previews the resulting balance', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/admin/users')
  await page.getByRole('button', { name: '管理 creator1@example.com' }).click()
  await page.getByRole('menuitem', { name: '发放积分' }).click()
  const d = page.getByRole('dialog')
  await d.getByLabel('发放数量').fill('0')
  await d.getByRole('button', { name: '发放积分', exact: true }).click()
  await expect(d.getByRole('alert')).toContainText('1–1,000,000')
  await d.getByLabel('发放数量').fill('25')
  await expect(d).toContainText('发放后可用积分：535')
  await d.getByRole('button', { name: '发放积分', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'creator1@example.com' })).toContainText('535')
})
test('temporary password exists only in the account creation result', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/admin/users')
  await page.getByRole('button', { name: '新建账号', exact: true }).click()
  const d = page.getByRole('dialog')
  await d.getByLabel('邮箱').fill('new@example.com')
  await d.getByRole('button', { name: '新建账号', exact: true }).click()
  await expect(d.getByLabel('临时密码')).toHaveValue('demo-temporary-9R!')
  await expect(d).toContainText('只显示这一次')
  await d.getByRole('button', { name: '我已保存，关闭' }).click()
  await expect(page.locator('input[value="demo-temporary-9R!"]')).toHaveCount(0)
  await page.getByRole('button', { name: '新建账号', exact: true }).click()
  await expect(page.getByLabel('临时密码')).toHaveCount(0)
})
test('search and pagination do not silently omit later users', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/admin/users')
  await expect(page.getByRole('row')).toHaveCount(26)
  await page.getByRole('button', { name: '加载更多用户' }).click()
  await expect(page.getByRole('row')).toHaveCount(29)
  await page.getByRole('textbox', { name: '搜索邮箱或手机' }).fill('creator27')
  await expect(page.getByRole('row')).toHaveCount(2)
  await expect(page.getByRole('row').last()).toContainText('creator27@example.com')
})
test('loading and failed admin data are visible and retryable', async ({ page }) => {
  await useDemoApi(page)
  let fail = true
  await page.route('**/api/v1/admin/users?**', (r) => (fail ? r.fulfill({ status: 500, json: { code: 'internal' } }) : r.fallback()))
  await page.goto('/admin/users')
  await expect(page.getByRole('button', { name: '重试' })).toBeVisible({ timeout: 15000 })
  fail = false
  await page.getByRole('button', { name: '重试' }).click()
  await expect(page.getByRole('row')).toHaveCount(26)
})
test('non-admin accounts cannot enter the admin shell', async ({ page }) => {
  await useDemoApi(page)
  await page.route('**/api/v1/me', (r) => r.fulfill({ json: { biz_id: 'member', is_admin: false, balance: 0, held: 0, entitlements: [] } }))
  await page.goto('/admin/users')
  await expect(page).not.toHaveURL(/admin/)
})
