import { test, expect, type Page } from '@playwright/test'
import { useDemoApi } from './demo'

const detail = (page: Page) => page.getByRole('complementary', { name: /预设详情|新建预设/ })

test('category and source live in the URL; system presets are read-only', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/presets')
  await expect(page.getByRole('button', { name: '查看 水彩' })).toBeVisible()
  await page.getByRole('tab', { name: '灯光' }).click()
  await expect(page).toHaveURL(/category=lighting/)
  await expect(page.getByRole('button', { name: '查看 黄金时刻' })).toBeVisible()
  await expect(page.getByRole('button', { name: '查看 水彩' })).toHaveCount(0)

  await page.getByRole('button', { name: '查看 黄金时刻' }).click()
  const d = detail(page)
  await expect(d).toContainText('系统预设')
  await expect(d.getByRole('textbox', { name: '描述词片段' })).toHaveAttribute('readonly', '')
  await expect(d.getByRole('textbox', { name: '预设名称' })).toHaveAttribute('readonly', '')
  await expect(d).toContainText('系统预设不能修改或删除')
  await expect(d.getByRole('button', { name: '删除预设' })).toHaveCount(0)
  await expect(d.getByRole('button', { name: '保存修改' })).toHaveCount(0)

  await page.getByRole('radio', { name: '我的' }).click()
  await expect(page).toHaveURL(/source=mine/)
  await expect(page.getByText('还没有自己的预设')).toBeVisible()
})

test('several presets are applied together, keeping the draft and naming what was added', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/create/image')
  await page.getByRole('combobox', { name: '描述画面' }).fill('海边的红色电车')
  await page.waitForTimeout(500)
  await page.getByRole('navigation').getByRole('link', { name: '风格预设' }).first().click()
  await page.getByRole('button', { name: '选择 水彩' }).click()
  await page.getByRole('button', { name: '选择 漫画' }).click()
  const tray = page.getByRole('region', { name: '已选择的预设' })
  await expect(tray).toContainText('已选 2 个')
  await tray.getByRole('button', { name: '移除 漫画' }).click()
  await expect(tray).toContainText('已选 1 个')
  await page.getByRole('tab', { name: '镜头' }).click()
  await page.getByRole('button', { name: '选择 特写' }).click()
  await expect(tray).toContainText('已选 2 个')
  await tray.getByRole('button', { name: '应用到创作' }).click()

  await expect(page).toHaveURL(/\/create\/image$/)
  await expect(page.getByText('已加入风格预设：水彩、特写')).toBeVisible()
  await expect(page.getByRole('combobox', { name: '描述画面' })).toHaveValue('海边的红色电车')
  await expect(page.getByRole('button', { name: '水彩、特写' })).toBeVisible()
})

test('a system preset saved as mine can be edited and deleted', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/presets')
  await page.getByRole('button', { name: '查看 水彩' }).click()
  await detail(page).getByRole('button', { name: '另存为我的预设' }).click()
  await expect(page.getByText('已另存为我的预设')).toBeVisible()
  await expect(page).toHaveURL(/source=mine/)
  const d = detail(page)
  await expect(d).toContainText('我的预设')
  const fragment = d.getByRole('textbox', { name: /描述词片段/ })
  await expect(d.getByRole('textbox', { name: /预设名称/ })).toHaveValue('水彩（副本）')
  await fragment.fill('水彩质感，更淡的色彩')
  await d.getByRole('button', { name: '保存修改' }).click()
  await expect(page.getByText('预设已保存')).toBeVisible()

  await d.getByRole('button', { name: '删除预设' }).click()
  const dialog = page.getByRole('alertdialog').or(page.getByRole('dialog'))
  await expect(dialog).toContainText('删除预设「水彩（副本）」？')
  await dialog.getByRole('button', { name: '删除预设' }).click()
  await expect(page.getByText('预设已删除')).toBeVisible()
  await expect(page.getByRole('button', { name: '查看 水彩（副本）' })).toHaveCount(0)
})

test('a new preset needs a name and a fragment, and lands in its category', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/presets')
  await page.getByRole('button', { name: '新建预设' }).first().click()
  const d = detail(page)
  await d.getByRole('button', { name: '创建预设' }).click()
  await expect(d.getByText('请填写预设名称')).toBeVisible()
  await expect(d.getByText('请填写描述词片段')).toBeVisible()
  await d.getByRole('textbox', { name: /预设名称/ }).fill('夕阳逆光')
  await d.getByRole('textbox', { name: /描述词片段/ }).fill('夕阳逆光，人物边缘发光')
  await d.getByRole('combobox', { name: '所属分类' }).selectOption({ label: '灯光' })
  await d.getByRole('button', { name: '创建预设' }).click()
  await expect(page.getByText('预设已创建')).toBeVisible()
  await expect(page).toHaveURL(/category=lighting/)
  await expect(page).toHaveURL(/source=mine/)
  await expect(page.getByRole('button', { name: '查看 夕阳逆光' })).toBeVisible()
})

test('presets from a mode without presets open image creation', async ({ page }) => {
  await useDemoApi(page)
  await page.goto('/create/video')
  await page.getByRole('navigation').getByRole('link', { name: '风格预设' }).first().click()
  await page.getByRole('button', { name: '查看 水彩' }).click()
  await detail(page).getByRole('button', { name: '应用到创作' }).click()
  await expect(page).toHaveURL(/\/create\/image$/)
  await expect(page.getByText('已加入风格预设：水彩')).toBeVisible()
})

test('English: system presets use their English names', async ({ page }) => {
  await useDemoApi(page, { lang: 'en' })
  await page.goto('/presets')
  await expect(page.getByRole('heading', { name: 'Presets', level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: 'View Watercolor' })).toBeVisible()
  await page.getByRole('button', { name: 'Select Watercolor' }).click()
  await expect(page.getByRole('region', { name: 'Selected presets' })).toContainText('1 selected')
})
